package com.epos.backend.enums;

public enum AuditAction {

    CREATE, UPDATE, GET, DELETE, VIEW, LOGIN, LOGOUT, PAYMENT, APPROVE, REJECT, STOCK_IN, STOCK_OUT, STOCK_ADJUSTMENT, COMPLETE, CANCEL, OPEN, CLOSE, CURRENT_OPEN_SHIFT,
    SALES_DASHBOARD, DAILY_SALES, PAYMENT_METHOD, REFUND_PAYMENT, CASHIER_REPORT, PRODUCT_SALES, PRINT, REPRINT, SIMULATE, ACTIVE, DEACTIVE, SUSPEND, BLOCKED,
    REDEEM
}
