package com.epos.backend.enums;

public enum AuditType {

    CATEGORY, PRODUCT, SUPPLIER, PURCHASE, USER, AUTH, PAYMENT, TRANSACTION, STOCK_MOVEMENT, SYSTEM, POS_SALES, SALES_RETURN, CASHIER_SHIFT,
    REPORT, RECEIPT, PROMO, CUSTOMER_MEMBER, LOYALITY_POINT, SYSTEM_PARAMETER
    
}
