package com.epos.backend.enums;

public enum AuditAction {

    CREATE, UPDATE, GET, DELETE, VIEW, LOGIN, LOGOUT, PAYMENT, APPROVE, REJECT, STOCK_IN, STOCK_OUT, STOCK_ADJUSTMENT, COMPLETE, CANCEL, OPEN, CLOSE, CURRENT_OPEN_SHIFT
}
