package com.epos.backend.enums;

public enum LoyaltyPointType {

    EARN, REDEEM, EXPIRED, ADJUSTMENT_ADD, ADJUSTMENT_DEDUCT, REVERSE_EARN, REVERSE_REDEEM, RETURN_REVERSE_EARN, RETURN_RESTORE_REDEEM
}
