package com.epos.backend.enums;

public enum StockMovementType {

    IN, OUT, ADJUSTMENT, SALE, PURCHASE, PURCHASE_IN, SALES_CANCEL_REVERSAL, ADJUSTMENT_IN, ADJUSTMENT_OUT, RETURN, SALES_OUT,
    SALES_RETURN_IN, SALES_RETURN_CANCEL_OUT

}
